#ifndef ENUMINICIARSESION_H
#define	ENUMINICIARSESION_H

enum enumIniciarSesion {
    SESION_YA_INICIADA_MISMO_NUMERO,
    SESION_YA_INICIADA_OTRO_NUMERO,
    SESION_INICIADA_CORRECTAMENTE,
    NUMERO_NO_EXISTE
};

#endif	/* ENUMINICIARSESION_H */
